Organizations:
  - Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: OR('OrdererMSP.member')
      Writers:
        Type: Signature
        Rule: OR('OrdererMSP.member')
      Admins:
        Type: Signature
        Rule: OR('OrdererMSP.admin')
  - Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/Org1.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: >-
          OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client',
          'Org1MSP.member')
      Writers:
        Type: Signature
        Rule: >-
          OR('Org1MSP.admin', 'Org1MSP.member', 'Org1MSP.client',
          'Org1MSP.member')
      Admins:
        Type: Signature
        Rule: OR('Org1MSP.admin')
    AnchorPeers:
      - Host: peer0.Org1.com
        Port: 5051
  - Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/Org2.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: >-
          OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client',
          'Org2MSP.member')
      Writers:
        Type: Signature
        Rule: >-
          OR('Org2MSP.admin', 'Org2MSP.member', 'Org2MSP.client',
          'Org2MSP.member')
      Admins:
        Type: Signature
        Rule: OR('Org2MSP.admin')
    AnchorPeers:
      - Host: peer0.Org2.com
        Port: 8051
Capabilities:
  Channel:
    V1_4_3: true
  Orderer:
    V1_4_2: true
  Application:
    V1_4_2: true
    V1_2: false
    V1_1: false
Application:
  Organizations: null
Orderer:
  OrdererType: solo
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Addresses:
    - 'orderer.example.com:7050'
  Organizations: null
Channel:
  Capabilities:
    V1_4_3: true
Profiles:
  FirstOrdererGenesis:
    Capabilities:
      V1_4_3: true
    Orderer:
      Organizations:
        - Name: OrdererOrg
          ID: OrdererMSP
          MSPDir: crypto-config/ordererOrganizations/example.com/msp
      OrdererType: solo
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Capabilities:
        V1_4_2: true
      Addresses:
        - 'orderer.example.com:7050'
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: Org1MSP
            ID: Org1MSP
            MSPDir: crypto-config/peerOrganizations/Org1.com/msp
            AnchorPeers:
              - Host: peer0.Org1.com
                Port: 5051
          - Name: Org2MSP
            ID: Org2MSP
            MSPDir: crypto-config/peerOrganizations/Org2.com/msp
            AnchorPeers:
              - Host: peer0.Org2.com
                Port: 8051
  nanchannel2Profile:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - Name: Org1MSP
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/Org1.com/msp
          AnchorPeers:
            - Host: peer0.Org1.com
              Port: 5051
        - Name: Org2MSP
          ID: Org2MSP
          MSPDir: crypto-config/peerOrganizations/Org2.com/msp
          AnchorPeers:
            - Host: peer0.Org2.com
              Port: 8051
      Capabilities:
        V1_4_2: true
        V1_2: false
        V1_1: false
