version: '2'
services:
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - >-
        ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - >-
        ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - >-
        ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - 'orderer.example.com:/var/hyperledger/production/orderer'
    ports:
      - '7050:7050'
  peer0.Org1.com:
    container_name: peer0.Org1.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Org1.com
      - 'CORE_PEER_ADDRESS=peer0.Org1.com:5051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:5051'
      - 'CORE_PEER_CHAINCODEADDRESS=peer0.Org1.com:5052'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5052'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Org1.com:6051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org1.com:5051'
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - '/var/run/:/host/var/run/'
      - >-
        ../crypto-config/peerOrganizations/Org1.com/peers/peer0.Org1.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ../crypto-config/peerOrganizations/Org1.com/peers/peer0.Org1.com/tls:/etc/hyperledger/fabric/tls
      - 'peer0.Org1.com:/var/hyperledger/production'
    image: 'hyperledger/fabric-peer:latest'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '5051:5051'
  peer1.Org1.com:
    container_name: peer1.Org1.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Org1.com
      - 'CORE_PEER_ADDRESS=peer1.Org1.com:6051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:6051'
      - 'CORE_PEER_CHAINCODEADDRESS=peer1.Org1.com:6052'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6052'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Org1.com:5051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org1.com:6051'
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - '/var/run/:/host/var/run/'
      - >-
        ../crypto-config/peerOrganizations/Org1.com/peers/peer1.Org1.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ../crypto-config/peerOrganizations/Org1.com/peers/peer1.Org1.com/tls:/etc/hyperledger/fabric/tls
      - 'peer1.Org1.com:/var/hyperledger/production'
    image: 'hyperledger/fabric-peer:latest'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '6051:6051'
  peer0.Org2.com:
    container_name: peer0.Org2.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Org2.com
      - 'CORE_PEER_ADDRESS=peer0.Org2.com:8051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:8051'
      - 'CORE_PEER_CHAINCODEADDRESS=peer0.Org2.com:8052'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Org2.com:9051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org2.com:8051'
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - '/var/run/:/host/var/run/'
      - >-
        ../crypto-config/peerOrganizations/Org2.com/peers/peer0.Org2.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ../crypto-config/peerOrganizations/Org2.com/peers/peer0.Org2.com/tls:/etc/hyperledger/fabric/tls
      - 'peer0.Org2.com:/var/hyperledger/production'
    image: 'hyperledger/fabric-peer:latest'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '8051:8051'
  peer1.Org2.com:
    container_name: peer1.Org2.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Org2.com
      - 'CORE_PEER_ADDRESS=peer1.Org2.com:9051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:9051'
      - 'CORE_PEER_CHAINCODEADDRESS=peer1.Org2.com:9052'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Org2.com:8051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org2.com:9051'
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - '/var/run/:/host/var/run/'
      - >-
        ../crypto-config/peerOrganizations/Org2.com/peers/peer1.Org2.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ../crypto-config/peerOrganizations/Org2.com/peers/peer1.Org2.com/tls:/etc/hyperledger/fabric/tls
      - 'peer1.Org2.com:/var/hyperledger/production'
    image: 'hyperledger/fabric-peer:latest'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '9051:9051'
  peer0.Org3.com:
    container_name: peer0.Org3.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Org3.com
      - 'CORE_PEER_ADDRESS=peer0.Org3.com:10051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:10051'
      - 'CORE_PEER_CHAINCODEADDRESS=peer0.Org3.com:10052'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Org3.com:11051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org3.com:10051'
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
      - '/var/run/:/host/var/run/'
      - >-
        ../crypto-config/peerOrganizations/Org3.com/peers/peer0.Org3.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ../crypto-config/peerOrganizations/Org3.com/peers/peer0.Org3.com/tls:/etc/hyperledger/fabric/tls
      - 'peer0.Org3.com:/var/hyperledger/production'
    image: 'hyperledger/fabric-peer:latest'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '10051:10051'
  peer1.Org3.com:
    container_name: peer1.Org3.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Org3.com
      - 'CORE_PEER_ADDRESS=peer1.Org3.com:11051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:11051'
      - 'CORE_PEER_CHAINCODEADDRESS=peer1.Org3.com:11052'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Org3.com:10051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org3.com:11051'
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
      - '/var/run/:/host/var/run/'
      - >-
        ../crypto-config/peerOrganizations/Org3.com/peers/peer1.Org3.com/msp:/etc/hyperledger/fabric/msp
      - >-
        ../crypto-config/peerOrganizations/Org3.com/peers/peer1.Org3.com/tls:/etc/hyperledger/fabric/tls
      - 'peer1.Org3.com:/var/hyperledger/production'
    image: 'hyperledger/fabric-peer:latest'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - '11051:11051'
